package com.tydic.bean;

import java.math.BigDecimal;
import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.USER_ID
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.TELE_TYPE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String teleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.DEVICE_NUMBER
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String deviceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.USER_PWD
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.USER_STATUS
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.CREATE_DATE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.ACTIVE_DATE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private Date activeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.USER_TYPE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.PREPAY_FLAG
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String prepayFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.LOCAL_NET
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String localNet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.DEVELOP_CHANNEL_ID
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String developChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.PROTO_FLAG
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String protoFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.SUB_USER_STATUS
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String subUserStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.STOP_DATE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private Date stopDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.VALID_FLAG
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String validFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.PRODUCT_ID
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.OPERATORS_TYPE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String operatorsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.MAIN_OFR_ID
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String mainOfrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.BRAND_CODE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String brandCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.FLAG_4G
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String flag4g;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.DEVELOP_NUMBER
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String developNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.THIRD_CHANNEL_CODE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String thirdChannelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.USER_MON_LIMIT
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private BigDecimal userMonLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFO_USER.MON_LIMIT_FLAG
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    private String monLimitFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.USER_ID
     *
     * @return the value of INFO_USER.USER_ID
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.USER_ID
     *
     * @param userId the value for INFO_USER.USER_ID
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.TELE_TYPE
     *
     * @return the value of INFO_USER.TELE_TYPE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getTeleType() {
        return teleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.TELE_TYPE
     *
     * @param teleType the value for INFO_USER.TELE_TYPE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setTeleType(String teleType) {
        this.teleType = teleType == null ? null : teleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.DEVICE_NUMBER
     *
     * @return the value of INFO_USER.DEVICE_NUMBER
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.DEVICE_NUMBER
     *
     * @param deviceNumber the value for INFO_USER.DEVICE_NUMBER
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber == null ? null : deviceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.USER_PWD
     *
     * @return the value of INFO_USER.USER_PWD
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.USER_PWD
     *
     * @param userPwd the value for INFO_USER.USER_PWD
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.USER_STATUS
     *
     * @return the value of INFO_USER.USER_STATUS
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.USER_STATUS
     *
     * @param userStatus the value for INFO_USER.USER_STATUS
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.CREATE_DATE
     *
     * @return the value of INFO_USER.CREATE_DATE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.CREATE_DATE
     *
     * @param createDate the value for INFO_USER.CREATE_DATE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.ACTIVE_DATE
     *
     * @return the value of INFO_USER.ACTIVE_DATE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public Date getActiveDate() {
        return activeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.ACTIVE_DATE
     *
     * @param activeDate the value for INFO_USER.ACTIVE_DATE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setActiveDate(Date activeDate) {
        this.activeDate = activeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.USER_TYPE
     *
     * @return the value of INFO_USER.USER_TYPE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.USER_TYPE
     *
     * @param userType the value for INFO_USER.USER_TYPE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.PREPAY_FLAG
     *
     * @return the value of INFO_USER.PREPAY_FLAG
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getPrepayFlag() {
        return prepayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.PREPAY_FLAG
     *
     * @param prepayFlag the value for INFO_USER.PREPAY_FLAG
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setPrepayFlag(String prepayFlag) {
        this.prepayFlag = prepayFlag == null ? null : prepayFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.LOCAL_NET
     *
     * @return the value of INFO_USER.LOCAL_NET
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getLocalNet() {
        return localNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.LOCAL_NET
     *
     * @param localNet the value for INFO_USER.LOCAL_NET
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setLocalNet(String localNet) {
        this.localNet = localNet == null ? null : localNet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.DEVELOP_CHANNEL_ID
     *
     * @return the value of INFO_USER.DEVELOP_CHANNEL_ID
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getDevelopChannelId() {
        return developChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.DEVELOP_CHANNEL_ID
     *
     * @param developChannelId the value for INFO_USER.DEVELOP_CHANNEL_ID
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setDevelopChannelId(String developChannelId) {
        this.developChannelId = developChannelId == null ? null : developChannelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.PROTO_FLAG
     *
     * @return the value of INFO_USER.PROTO_FLAG
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getProtoFlag() {
        return protoFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.PROTO_FLAG
     *
     * @param protoFlag the value for INFO_USER.PROTO_FLAG
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setProtoFlag(String protoFlag) {
        this.protoFlag = protoFlag == null ? null : protoFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.SUB_USER_STATUS
     *
     * @return the value of INFO_USER.SUB_USER_STATUS
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getSubUserStatus() {
        return subUserStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.SUB_USER_STATUS
     *
     * @param subUserStatus the value for INFO_USER.SUB_USER_STATUS
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setSubUserStatus(String subUserStatus) {
        this.subUserStatus = subUserStatus == null ? null : subUserStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.STOP_DATE
     *
     * @return the value of INFO_USER.STOP_DATE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public Date getStopDate() {
        return stopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.STOP_DATE
     *
     * @param stopDate the value for INFO_USER.STOP_DATE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setStopDate(Date stopDate) {
        this.stopDate = stopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.VALID_FLAG
     *
     * @return the value of INFO_USER.VALID_FLAG
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.VALID_FLAG
     *
     * @param validFlag the value for INFO_USER.VALID_FLAG
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setValidFlag(String validFlag) {
        this.validFlag = validFlag == null ? null : validFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.PRODUCT_ID
     *
     * @return the value of INFO_USER.PRODUCT_ID
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.PRODUCT_ID
     *
     * @param productId the value for INFO_USER.PRODUCT_ID
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.OPERATORS_TYPE
     *
     * @return the value of INFO_USER.OPERATORS_TYPE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getOperatorsType() {
        return operatorsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.OPERATORS_TYPE
     *
     * @param operatorsType the value for INFO_USER.OPERATORS_TYPE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setOperatorsType(String operatorsType) {
        this.operatorsType = operatorsType == null ? null : operatorsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.MAIN_OFR_ID
     *
     * @return the value of INFO_USER.MAIN_OFR_ID
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getMainOfrId() {
        return mainOfrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.MAIN_OFR_ID
     *
     * @param mainOfrId the value for INFO_USER.MAIN_OFR_ID
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setMainOfrId(String mainOfrId) {
        this.mainOfrId = mainOfrId == null ? null : mainOfrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.BRAND_CODE
     *
     * @return the value of INFO_USER.BRAND_CODE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getBrandCode() {
        return brandCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.BRAND_CODE
     *
     * @param brandCode the value for INFO_USER.BRAND_CODE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setBrandCode(String brandCode) {
        this.brandCode = brandCode == null ? null : brandCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.FLAG_4G
     *
     * @return the value of INFO_USER.FLAG_4G
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getFlag4g() {
        return flag4g;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.FLAG_4G
     *
     * @param flag4g the value for INFO_USER.FLAG_4G
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setFlag4g(String flag4g) {
        this.flag4g = flag4g == null ? null : flag4g.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.DEVELOP_NUMBER
     *
     * @return the value of INFO_USER.DEVELOP_NUMBER
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getDevelopNumber() {
        return developNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.DEVELOP_NUMBER
     *
     * @param developNumber the value for INFO_USER.DEVELOP_NUMBER
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setDevelopNumber(String developNumber) {
        this.developNumber = developNumber == null ? null : developNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.THIRD_CHANNEL_CODE
     *
     * @return the value of INFO_USER.THIRD_CHANNEL_CODE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getThirdChannelCode() {
        return thirdChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.THIRD_CHANNEL_CODE
     *
     * @param thirdChannelCode the value for INFO_USER.THIRD_CHANNEL_CODE
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setThirdChannelCode(String thirdChannelCode) {
        this.thirdChannelCode = thirdChannelCode == null ? null : thirdChannelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.USER_MON_LIMIT
     *
     * @return the value of INFO_USER.USER_MON_LIMIT
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public BigDecimal getUserMonLimit() {
        return userMonLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.USER_MON_LIMIT
     *
     * @param userMonLimit the value for INFO_USER.USER_MON_LIMIT
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setUserMonLimit(BigDecimal userMonLimit) {
        this.userMonLimit = userMonLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFO_USER.MON_LIMIT_FLAG
     *
     * @return the value of INFO_USER.MON_LIMIT_FLAG
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public String getMonLimitFlag() {
        return monLimitFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFO_USER.MON_LIMIT_FLAG
     *
     * @param monLimitFlag the value for INFO_USER.MON_LIMIT_FLAG
     *
     * @mbggenerated Mon Apr 23 23:19:49 CST 2018
     */
    public void setMonLimitFlag(String monLimitFlag) {
        this.monLimitFlag = monLimitFlag == null ? null : monLimitFlag.trim();
    }
}