package com.tydic.dao;

import com.tydic.bean.InfoUser;
import com.tydic.bean.InfoUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InfoUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_USER
     *
     * @mbggenerated Mon Apr 23 23:14:23 CST 2018
     */
    int countByExample(InfoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_USER
     *
     * @mbggenerated Mon Apr 23 23:14:23 CST 2018
     */
    int deleteByExample(InfoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_USER
     *
     * @mbggenerated Mon Apr 23 23:14:23 CST 2018
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_USER
     *
     * @mbggenerated Mon Apr 23 23:14:23 CST 2018
     */
    int insert(InfoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_USER
     *
     * @mbggenerated Mon Apr 23 23:14:23 CST 2018
     */
    int insertSelective(InfoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_USER
     *
     * @mbggenerated Mon Apr 23 23:14:23 CST 2018
     */
    List<InfoUser> selectByExample(InfoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_USER
     *
     * @mbggenerated Mon Apr 23 23:14:23 CST 2018
     */
    InfoUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_USER
     *
     * @mbggenerated Mon Apr 23 23:14:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") InfoUser record, @Param("example") InfoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_USER
     *
     * @mbggenerated Mon Apr 23 23:14:23 CST 2018
     */
    int updateByExample(@Param("record") InfoUser record, @Param("example") InfoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_USER
     *
     * @mbggenerated Mon Apr 23 23:14:23 CST 2018
     */
    int updateByPrimaryKeySelective(InfoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_USER
     *
     * @mbggenerated Mon Apr 23 23:14:23 CST 2018
     */
    int updateByPrimaryKey(InfoUser record);
}